name: pb_bem
channels:
  - conda-forge
  - defaults
  - eumetsat
dependencies:
  - fftw3
  - git
  - jupyter
  - llvmlite
  - mako
  - matplotlib
  - notebook
  - numba
  - numpy
  - ocl-icd
  - openblas=0.3.9
  - pip
  - plotly
  - pocl
  - pandas
  - pybind11
  - pyopencl
  - python
  - scipy
  - tbb
  - pip:
    - meshio
    - "git+https://github.com/bempp/bempp-cl.git@master"
    - "git+https://github.com/exafmm/exafmm-t.git@master"
    - "git+https://github.com/bem4solvation/bem_electrostatics.git@dev"